### ISSUE TITLE
When the pc sleeps and wakes from sleep, the device numbers change

### ISSUE THREAD

**Issue by chrdh** [andyvorld/LGSTrayBattery#63]
When the pc sleeps and wakes from sleep, the device numbers change, so maybe if i have my G935 before the sleep it was dev00000000, and after the wake up it will be dev00000002.

I create a rainmeter skin and it use the device number so if the number change when the pc sleep its a problem do you know how to solve it please ?

(sorry for my english)
thanks !

**Comment by andyvorld** [comment]
Yeah, I think thats an issue with how G Hub is enumerating the devices, I made a new release so that you can request device telemetry via the device name now (e.g. `http://localhost:12321/device/G403%20Prodigy%20Gaming%20Mouse%20Wireless`).
Note if you have multiple devices with the same name, only the first one will be returned (By order of discovery).

https://github.com/andyvorld/LGSTrayBattery/releases/tag/v2.1.3

**Comment by chrdh** [comment]
thank you so much sir ! <3

**Comment by chrdh** [comment]
that for you and the community if you want to share it, its the rainmeter skin : 
https://drive.google.com/file/d/1_Cv-2Oc3KjYWL12KMx04v6fckQR-IXS3/view?usp=sharing
i do it for G935, G915, MX MASTER, but its easy to modify the .ini file !
thank you sir !

**Comment by andyvorld** [comment]
No problem.
