### ISSUE TITLE
Support more devices

### ISSUE THREAD

**Issue by BriceBoy** [andyvorld/LGSTrayBattery#9]
Hey Do you think you could do the same but with other Logitech devices ? I'm currently using G915, G502 wireless and G733 and looking for the exact thing you did. I would love to use your app with my devices

**Comment by andyvorld** [comment]
The G502 should work fine since it is a modern logitech mouse.
Have you tested the G915 with the program? As from what I remember keyboards and mouses are dealt with by Logitech quite similarly.
If it doesn't work, I don't think I can really do much, similarly with the G733 as I only have access to two Logitech mouses with me, a G403 and MX Anywhere 2S.

**Comment by BriceBoy** [comment]
I just tried and it seems to recognize the G915 and the G502. But the problem is that it doesn't show any battery percentage. And for the G733 maybe I could help you and give you informations needed to implement it ?

**Comment by andyvorld** [comment]
I am assuming that for the G915 and G502 are showing a voltage but not a percentage, I just wrote another script to pull the missing power models from Logitech G hub, https://github.com/andyvorld/LGSTrayBattery_GHUB_dump/releases/tag/v0.1

Im not sure on how I would approach the G733, as this repo's code is made from reverse engineering the keyboard and mouse drivers so that it does not rely on LGS or GHUB, so unless the G733 is emulated like a keyboard or mouse, I don't really know how to proceed. 

From the GHUB dump code, I found a way to tap into the official Logitech agent for telemetry rather than using native drivers. I might have a look into producing an alternate program that uses that method for battery level tracking, at the cost of having GHUB running in the background.

**Comment by andyvorld** [comment]
I just wrote a seperate program that depends on Logitech G HUB running in the background, while it might not fufill the idea of battery management without it, it should support every device that G HUB supports,

https://github.com/andyvorld/LGSTrayBattery_GHUB

**Comment by BriceBoy** [comment]
It works so well ! I'm really satisfied with this thx a lot
